version: '3.8'

services:
  backend:
    image: chandrujp/csharp-analyzer-backend:latest
    container_name: backend
    ports:
      - "5000:5000"

  frontend:
    image: chandrujp/dto_agent:latest
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
